name: Ryan_Env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - ld_impl_linux-64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.44.2
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.2.0
  - pip=23.3.1
  - python=3.11.6
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - absl-py==2.0.0
      - numpy==1.26.2
      - ortools==9.8.3296
      - pandas==2.1.3
      - protobuf==4.25.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - six==1.16.0
      - tzdata==2023.3

